### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by mkairanbay** [nlpub/pymystem3#35] opened 2019-10-10 10:29 UTC
when I call m = Mystem() it gives me an error "permission denied". 
Installing mystem to /Users/magzhankairanbay/.local/bin/mystem from http://download.cdn.yandex.net/mystem/mystem-3.1-macosx.tar.gz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/magzhankairanbay/anaconda3/lib/python3.6/site-packages/pymystem3/mystem.py", line 178, in __init__
    autoinstall()
  File "/Users/magzhankairanbay/anaconda3/lib/python3.6/site-packages/pymystem3/mystem.py", line 57, in autoinstall
    install(out)
  File "/Users/magzhankairanbay/anaconda3/lib/python3.6/site-packages/pymystem3/mystem.py", line 88, in install
    tar.extract(MYSTEM_EXE, MYSTEM_DIR)
  File "/Users/magzhankairanbay/anaconda3/lib/python3.6/tarfile.py", line 2052, in extract
    numeric_owner=numeric_owner)
  File "/Users/magzhankairanbay/anaconda3/lib/python3.6/tarfile.py", line 2122, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/Users/magzhankairanbay/anaconda3/lib/python3.6/tarfile.py", line 2163, in makefile
    with bltn_open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: '/Users/magzhankairanbay/.local/bin/mystem'

I am using Mac

**Comment by mkairanbay** [comment] 2019-10-10 10:52
SOlved this problem by extracting the tar file in separate folder and copy mystem exe to required place. In my case, it was: `sudo cp mystem /Users/magzhankairanbay/.local/bin`

**Comment by alexanderpanchenko** [comment] 2019-10-11 08:42
Hello, thank you for this report. I will close the issue for now if the problem is solved.

**Closed by alexanderpanchenko** 2019-10-11 08:42 UTC

**Comment by alexAmaguaya95** [comment] 2022-06-13 16:51
I have the same problem, but I'm using azure databricks.

![Screenshot from 2022-06-13 11-50-43](https://user-images.githubusercontent.com/99046306/173404740-4fd39a08-88df-4abf-a08b-691a27bd33ae.png)
