### ISSUE TITLE
Hangs in Google Colab

### ISSUE THREAD

**Issue by ukoloff** [nlpub/pymystem3#28] opened 2018-11-15 07:37 UTC
In [Google Colab](https://colab.research.google.com/) `pymystem3` succesfuly installed, imported, but lemmatization itself hangs and never stops

See [example](https://colab.research.google.com/drive/1vG0FxD2hGlf99VmwX8xtPg-dpGfPm4Iy).

**Comment by alexanderpanchenko** [comment] 2018-11-15 09:08
Thanks. I never used Colab before and do not know specificities of this environment. 


I've just tried on Ubuntu 16.04 server and it works (any suggestion and patch to support Colab is welcome!): 
```
(root) panchenko@ltnode1a:~/sensegram/model$ python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
(root) panchenko@ltnode1a:~/sensegram/model$ pip install pymystem3
Collecting pymystem3
  Downloading https://files.pythonhosted.org/packages/00/8c/98b43c5822620458704e187a1666616c1e21a846ede8ffda493aabe11207/pymystem3-0.2.0-py3-none-any.whl
Requirement already satisfied: requests in /home/panchenko/anaconda/lib/python3.6/site-packages (from pymystem3) (2.18.4)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/panchenko/anaconda/lib/python3.6/site-packages (from requests->pymystem3) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /home/panchenko/anaconda/lib/python3.6/site-packages (from requests->pymystem3) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/panchenko/anaconda/lib/python3.6/site-packages (from requests->pymystem3) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /home/panchenko/anaconda/lib/python3.6/site-packages (from requests->pymystem3) (2018.1.18)
Installing collected packages: pymystem3
Successfully installed pymystem3-0.2.0
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(root) panchenko@ltnode1a:~/sensegram/model$ pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 1.1MB/s
Installing collected packages: pip
  Found existing installation: pip 18.0
    Uninstalling pip-18.0:
      Successfully uninstalled pip-18.0
Successfully installed pip-18.1
(root) panchenko@ltnode1a:~/sensegram/model$ ipython
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pymystem3 import Mystem

In [2]: m = Mystem()
Installing mystem to /home/panchenko/.local/bin/mystem from http://download.cdn.yandex.net/mystem/mystem-3.1-linux-64bit.tar.gz

In [3]: m.lemmatize("Красивая мама красиво мыла раму")
Out[3]: ['красивый', ' ', 'мама', ' ', 'красиво', ' ', 'мыть', ' ', 'рама', '\n']
```

**Comment by alexanderpanchenko** [comment] 2018-11-15 14:00
seems that colab uses some version of ubuntu 18.04: 

 
![image](https://user-images.githubusercontent.com/1456830/48557292-6bec1400-e8f7-11e8-9b53-7ea8d7bcbc35.png)

on my ubuntu 18.04 box it works (anaconda 3):

![image](https://user-images.githubusercontent.com/1456830/48557462-e3ba3e80-e8f7-11e8-9ca9-33c906e0310b.png)

**Comment by alexanderpanchenko** [comment] 2018-11-15 14:05
i guess the problem is with some hardware/resource limits of the free colab accounts, not sure which ones however...

**Comment by ukoloff** [comment] 2018-11-20 07:04
> Hi! Any luck so far? 

I'm afraid no progress yet.

**Comment by alexanderpanchenko** [comment] 2018-11-20 08:39
Hello, the library communicates with the mystem binary using pipes. Maybe colab somehow restricted this system communications. I do not know how to fix it at the moment, but a patch is welcome.

**Comment by nokados** [comment] 2019-10-01 21:30
It works with pymystem==0.1.10
(mystem from http://download.cdn.yandex.net/mystem/mystem-3.0-linux3.1-64bit.tar.gz)
If you have already installed pymystem==0.2.0, then it probably installed mystem 3.1. In this case, you need to delete mystem or reset your runtime.

**Comment by alexanderpanchenko** [comment] 2019-10-11 08:44
once the issue was with the versions i will close this issue

**Closed by alexanderpanchenko** 2019-10-11 08:44 UTC

**Comment by brs1977** [comment] 2020-02-28 06:01
copy mystem3 to /bin

!wget http://download.cdn.yandex.net/mystem/mystem-3.0-linux3.1-64bit.tar.gz
!tar -xvf mystem-3.0-linux3.1-64bit.tar.gz
!cp mystem /bin

**Comment by skinenbayev** [comment] 2020-05-21 19:46
try this !pip install git+https://github.com/nlpub/pymystem3

**Comment by gushart** [comment] 2020-08-14 09:45
> copy mystem3 to /bin
> 
> !wget http://download.cdn.yandex.net/mystem/mystem-3.0-linux3.1-64bit.tar.gz
> !tar -xvf mystem-3.0-linux3.1-64bit.tar.gz
> !cp mystem /bin

Doesn't work

**Comment by gushart** [comment] 2020-08-14 09:48
14.08 edit copy:

!wget http://download.cdn.yandex.net/mystem/mystem-3.0-linux3.1-64bit.tar.gz
!tar -xvf mystem-3.0-linux3.1-64bit.tar.gz
!cp mystem /root/.local/bin/mystem

**Comment by vadimvik** [comment] 2020-09-17 07:42
> 14.08 edit copy:
> 
> !wget http://download.cdn.yandex.net/mystem/mystem-3.0-linux3.1-64bit.tar.gz
> !tar -xvf mystem-3.0-linux3.1-64bit.tar.gz
> !cp mystem /root/.local/bin/mystem

And thanks to "gushart", it works.

**Comment by EvgenyNovashov** [comment] 2021-02-08 05:53
I tryed use advice gushart, but Colab gave error cp: failed to access '/root/.local/bin/mystem': Not a directory
I resolved problem: !pip install pymystem3==0.1.10

**Comment by NikitaTsekh** [comment] 2022-02-04 12:35
Same problem with Google Collab, and home version of Jupyter Notebook. While on the inner server of Yandex (I am a student and was given acess to inner Yandex Jupyter Notebook) lemmatization is done in seconds!

**Comment by Raygeku** [comment] 2022-06-16 06:03
> 14.08 edit copy:
> 
> !wget http://download.cdn.yandex.net/mystem/mystem-3.0-linux3.1-64bit.tar.gz !tar -xvf mystem-3.0-linux3.1-64bit.tar.gz !cp mystem /root/.local/bin/mystem

I had same problem but with Py app in docker container and copying mystem unpacked file to /bin directory works for me.
